### ISSUE TITLE
Images spanning both columns?

### ISSUE THREAD

**Issue by donnekgit** [joseareia/nob-article#1]
Very nice template. 

Is there any way to allow an image which spans both columns in a two-column layout?

**Comment by joseareia** [comment]
Hello @donnekgit!

Yes, you can use the following environment: `\begin{figure*}` instead of the regular `\begin{figure}`.

I hope it helped!

**Comment by donnekgit** [comment]
Hi José
Thanks for coming back so quickly.  Yes, that works great!
